# -*- coding: utf-8 -*-
"""SEM6_MJ.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NQeI_Ojsdj4zi2AbA062pn_31Z9RcjNh

<h1 style="font-size:350%;"><center><b style="color:navy;">EDA and Classification of Malignant and Benign Tumors</b></center></h1>
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv("/content/data.csv")

"""# DATA CLEANING"""

data.head()

data.shape

data.columns

data.diagnosis.value_counts()

"""## MISSING VALUES"""

# Check for null values:
data.isnull().sum()

#drop the unnamed column:
data.drop(['Unnamed: 32', 'id'], axis=1, inplace=True)

# statistics of our data:
data.describe().T

"""# DATA VISUALIZATION"""

from sklearn.preprocessing import LabelEncoder
from scipy import stats

label_encoder = LabelEncoder()
data['diagnosis_encoded'] = label_encoder.fit_transform(data['diagnosis'])

correlations = {}
for column in data.columns:
  if column != 'diagnosis' and column != 'diagnosis_encoded' and data[column].dtype != object:
    correlation, p_value = stats.pointbiserialr(data['diagnosis_encoded'], data[column])
    correlations[column] = correlation

corr_df = pd.DataFrame.from_dict(correlations, orient='index', columns=['Correlation with Diagnosis'])
print(corr_df)

# Analyzing the target variable

plt.title('Count of cancer type')
sns.countplot(data['diagnosis'])
plt.xlabel('Cancer lethality')
plt.ylabel('Count')
plt.show()

#plot the histograms for each feature:
data.hist(figsize = (30,30), color = 'orange')
plt.show()

melted_data = pd.melt(data,id_vars = "diagnosis",value_vars = ['radius_worst', 'texture_worst', 'perimeter_worst'])
plt.figure(figsize = (15,10))
sns.boxplot(x = "variable", y = "value", hue="diagnosis",data= melted_data)
plt.show()

data.columns

#generate a scatter plot with the following columns:

columns = ['diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean', 'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean']

sns.pairplot(data=data[columns], hue="diagnosis", palette='rocket')

# Distribution density plot KDE (kernel density estimate)
sns.FacetGrid(data, hue="diagnosis", height=6).map(sns.kdeplot, "radius_mean").add_legend()
plt.show()

# Plotting the distribution of the mean radius
sns.stripplot(x="diagnosis", y="radius_mean", data=data, jitter=True, edgecolor="gray")
plt.show()

"""<h1>Drop the Columns with high correlation</h1>"""

#From the correlation matrix we got to knwo that these columns are highly correlated with radius_mean, perimeter, area columns.
# So we are dropping these columns:

# first, drop all "worst" columns
cols_to_drop = ['radius_worst',
                'texture_worst',
                'perimeter_worst',
                'area_worst',
                'smoothness_worst',
                'compactness_worst',
                'concavity_worst',
                'concave points_worst',
                'symmetry_worst',
                'fractal_dimension_worst',
                'perimeter_mean',
                'perimeter_se',
                'area_mean',
                'area_se',
                'concavity_mean',
                'concavity_se',
                'concave points_mean',
                'concave points_se',
                'id']

# Keep only the columns that are NOT in cols_to_drop
data = data[[col for col in data.columns if col not in cols_to_drop]]

# verify remaining columns
data.columns

corr = data.drop(columns=['diagnosis']).corrwith(data['diagnosis_encoded']).round(2) # Changed to use corrwith and diagnosis_encoded

#Convert to DataFrame for heatmap
corr_df = pd.DataFrame(corr, columns=['Correlation with Diagnosis'])

# Define custom colormap
cmap = sns.diverging_palette(220, 10, as_cmap=True)

# mask = np.zeros_like(corr, dtype=np.bool) # Mask is not needed for single column correlation
# mask[np.triu_indices_from(mask)] = True

f, ax = plt.subplots(figsize=(20, 5)) # Adjusted figsize for single column
sns.heatmap(corr_df.transpose(), cmap=cmap, vmin=-1, vmax=1, center=0,
            square=True, linewidths=.5, cbar_kws={"shrink": .5}, annot=True) # Modified heatmap call
plt.tight_layout()

"""# TRAIN TEST SPLIT"""

# Spliting target variable and independent variables
X = data.drop(['diagnosis'], axis = 1)
y = data['diagnosis']

# Splitting the data into training set and testset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state = 0)
print("Size of training set:", X_train.shape)
print("Size of training set:", X_test.shape)

"""# Random Forest Model"""

from sklearn.preprocessing import StandardScaler
from xgboost import XGBClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, classification_report

# Random Forest Classifier

# Import library of RandomForestClassifier model
from sklearn.ensemble import RandomForestClassifier

# Create a Random Forest Classifier
rf = RandomForestClassifier()

# Hyperparameter Optimization
parameters = {'n_estimators': [4, 6, 9, 10, 15],
              'max_features': ['log2', 'sqrt','auto'],
              'criterion': ['entropy', 'gini'],
              'max_depth': [2, 3, 5, 10],
              'min_samples_split': [2, 3, 5],
              'min_samples_leaf': [1, 5, 8]
             }


# Train the model using the training sets
rf.fit(X_train,y_train)

y_rf_pred = rf.predict(X_test)

from sklearn import metrics
acc_rf = round( metrics.accuracy_score(y_test, y_rf_pred) * 100 , 2 )
print( 'Accuracy of Random Forest model : ', acc_rf )

"""# Support Vector Machine"""

# SVM Classifier
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

from sklearn import svm

svc = svm.SVC()

parameters = [
  {'C': [1, 10, 100, 1000], 'kernel': ['linear']},
  {'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001], 'kernel': ['rbf']},
]

grid_obj = GridSearchCV(svc, parameters)
grid_obj = grid_obj.fit(X_train, y_train)

svc = grid_obj.best_estimator_

svc.fit(X_train,y_train)

# Prediction on test data
y_pred = svc.predict(X_test)

acc_svm = round( metrics.accuracy_score(y_test, y_pred) * 100, 2 )
print( 'Accuracy of SVM model : ', acc_svm )

from sklearn.linear_model import LogisticRegression
model = LogisticRegression(random_state=42)
model.fit(X_train, y_train)
y_lr_pred = svc.predict(X_test)
print(y_lr_pred)

# Logistic Regression Classifier
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler # Import StandardScaler


scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

model_lr = LogisticRegression(random_state=42)
model_lr.fit(X_train_scaled, y_train)

y_lr_pred = model_lr.predict(X_test_scaled)

acc_lr = round(metrics.accuracy_score(y_test, y_lr_pred) * 100, 2)
print('Accuracy of LR model : ', acc_lr)

"""# CONCLUSION

<p style="font-size:180%;">In this Kernel i have performed EDA, and built the machine learning models(RF, SVM)</p>

<p style="font-size:180%;">If you like the kernel, please give an upvote.</p>
"""

sample = pd.read_csv("/data_sampled.csv")
sample = sample[[col for col in sample.columns if col in X.columns and col != 'diagnosis']]

sample['diagnosis_encoded'] = 0

sample_pred = rf.predict(sample)
if sample_pred=='B':
  print("The tumor is benign")
else:
  print("The tumor is malignant")

def predict_survival_rate(tumor_stage, age, gender):
    """Predicts the survival rate based on tumor stage, age, and gender."""

    if tumor_stage == "B":
        if age < 50:
            survival_rate = 0.97
        else:
            survival_rate = 0.99
    elif tumor_stage == "M":
        if age < 50:
            survival_rate = 0.38
        else:
            survival_rate = 0.26
    else:
        return "Invalid tumor stage."

    return f"Predicted survival rate: {survival_rate * 100:.1f}%"


#user input
age = int(input("Enter the patient's age: "))
gender = input("Enter the patient's gender (Male/Female): ")
tumor_stage = input("Enter the tumor type(B or M): ")

survival_prediction = predict_survival_rate(tumor_stage, age, gender)
survival_prediction